Update overview.md
valtimo-platform/valtimo-documentation pull request #42
Opened 2022-08-14 10:10 UTC by rutger-h

2022-08-15 12:36 UTC, mritense commented
We just published a style guide here: https://github.com/valtimo-platform/valtimo-documentation/blob/main/STYLE-GUIDE.md. Please take a look at it, some of the text in this commit does not conform to it. For example, use of the third person plural, use of colloquial language ('overkill').

2022-08-15 12:39 UTC, mritense requested changes
Conform to style guide

2022-09-13 08:47 UTC, marijnritense approved these changes

2022-09-13 08:57 UTC, mritense approved these changes

2022-09-13 08:57 UTC, merged